### ISSUE TITLE
Hipstr QA

### ISSUE THREAD

**Issue by daveroma** [Catatek/bookhipstr#50]

**Comment by daveroma** [comment]
**Mobile**
- Please Change Contact to Contact Us in Mobile menu
- Contact link is broken on mobile - should link to Book Now page 

**JotForm**
Filling out JotForm redirects to bookhipstr.com’s thank you page “thank you Page”. 

**Tracking Code:**
Please include all tracking code on new site: 

You can find the Google Analytics snippet in the markup of the current page, search for UA-54974019-1

You can find the Facebook Pixel snippet in the markup of the current page, search for 182915612330648

**Home Page**

Card order:
- Hipstr Mosaic Wall 
- Hipstr Array plus
- Hipstr Ridiculous Photo Booth Package
- Hipstr Flow Cam
- Hipstr Gif Booth
- Hipstr Retail Installments
- Hipstr Hashtag Instaprint

Please Remove the VR/AR card (and page)

Hipstr array plus card icon gif should be animated like on existing site

“We’ll be there for you” is jumping out of its container on mobile
[screenshot]

For the  black container that reads “Trusted by Great Companies and Great People” the animation is coming in lightning fast and should slow down and float up similar to the other animation text the came before it. 

**Hipstr Mosaic Wall Page**
- Hero section Title should read: “Hipstr Mosaic Wall” - Hipstr should be in the orange and the rest of the hero title should be white

**Hipstr Array Plus Page**
- Hero section Title should read: “Hipstr Array Plus” - Hipstr should be in the orange and the rest of the hero title should be white
- Please Change Hero Image to [screenshot below]

**Hipstr’s Ridiculous Photo Booth Package** 
- Please Remove copy: “You’re about to get all the things.”
- Video is playing double audio

**Hipstr Flow Cam**
- Hero section Title should read: “Hipstr Flow Cam” - Hipstr should be in the orange and the rest of the hero title should be white

**Hipstr Gif Booth**
- Hero section Title should read: “Hipstr Gif Booth” - Hipstr should be in the orange and the rest of the hero title should be white

**Hipstr Retail Installments**
- Hero section Title should read: “Hipstr Retail Kiosk” - Hipstr should be in the orange and the rest of the hero title should be white

**Hipstr Hashtag Instaprint**
- Hero section Title should read: “Hipstr Hashtag Instaprint” - Hipstr should be in the orange and the rest of the hero title should be white
- Mike wants the Instagram style photos that are on the existing page - sorry I tried

**Hipstr AR/VR**
Please Remove this page

**Comment by daveroma** [comment]
<img width="265" alt="Screen Shot 2019-03-13 at 7 32 04 PM" src="https://user-images.githubusercontent.com/1719307/54322697-919ad880-45cc-11e9-98f9-f5d27fda655e.png">
<img width="509" alt="Screen Shot 2019-03-13 at 7 42 35 PM" src="https://user-images.githubusercontent.com/1719307/54322698-919ad880-45cc-11e9-8d38-a13db2827bb0.png">
<img width="340" alt="Screen Shot 2019-03-13 at 7 46 32 PM" src="https://user-images.githubusercontent.com/1719307/54322699-919ad880-45cc-11e9-8824-7cbf53412adb.png">

**Comment by wwwhatley** [comment]
- Hipstr array plus card icon gif should be animated like on existing site
- Mike wants the Instagram style photos that are on the existing page - sorry I tried
- Video is playing double audio / can't reproduce the bug
